export const DEFAULT_BASE_URL = 'https://api.doordeck.com'
export const BASE_URL = '4zA64daKfi'
export const EPHEMERAL_PRIKEY = 'S8Y0bEpu4y'
export const EPHEMERAL_PUBKEY = '4yA64dfKfi'
export const AUTH_TOKEN = '2uGGg077YR'
export const CERT = 'PAWx65jO4A'
